/*
 * Copyright 2016 HuntBugs contributors
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package one.util.huntbugs.detect;

import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

import com.strobel.assembler.metadata.FieldDefinition;
import com.strobel.assembler.metadata.FieldReference;
import com.strobel.assembler.metadata.Flags;
import com.strobel.assembler.metadata.MethodDefinition;
import com.strobel.assembler.metadata.MethodReference;
import com.strobel.assembler.metadata.TypeDefinition;
import com.strobel.assembler.metadata.TypeReference;
import com.strobel.assembler.metadata.annotations.CustomAnnotation;
import com.strobel.decompiler.ast.AstCode;
import com.strobel.decompiler.ast.Expression;

import one.util.huntbugs.db.FieldStats;
import one.util.huntbugs.registry.FieldContext;
import one.util.huntbugs.registry.MethodContext;
import one.util.huntbugs.registry.anno.AssertWarning;
import one.util.huntbugs.registry.anno.AstNodes;
import one.util.huntbugs.registry.anno.AstVisitor;
import one.util.huntbugs.registry.anno.FieldVisitor;
import one.util.huntbugs.registry.anno.WarningDefinition;
import one.util.huntbugs.util.Nodes;
import one.util.huntbugs.util.Types;
import one.util.huntbugs.warning.Roles;
import one.util.huntbugs.warning.WarningAnnotation;
import one.util.huntbugs.warning.WarningAnnotation.Location;

/**
 * @author lan
 *
 */
@WarningDefinition(category="RedundantCode", name="UnusedPrivateField", maxScore=45)
@WarningDefinition(category="RedundantCode", name="UnusedPublicField", maxScore=35)
@WarningDefinition(category="RedundantCode", name="UnreadPrivateField", maxScore=48)
@WarningDefinition(category="RedundantCode", name="UnreadPublicField", maxScore=32)
@WarningDefinition(category="Performance", name="FieldShouldBeStatic", maxScore=50)
public class FieldAccess {
    static class FieldRecord {
        MethodReference firstWriteMethod;
        Location firstWriteLocation;
        Object constant;
    }
    
    Map<String, FieldRecord> fields = new HashMap<>();
    
    @AstVisitor(nodes=AstNodes.EXPRESSIONS)
    public void visitCode(Expression expr, MethodContext mc, MethodDefinition md, TypeDefinition td) {
        
        if(expr.getCode() == AstCode.PutField || expr.getCode() == AstCode.PutStatic) {
            FieldDefinition fd = ((FieldReference) expr.getOperand()).resolve();
            if(fd != null && !fd.isSynthetic() && fd.getDeclaringType().isEquivalentTo(td)) {
                FieldRecord fieldRecord = fields.get(fd.getName());
                if(fieldRecord == null) {
                    fieldRecord = new FieldRecord();
                    fieldRecord.firstWriteMethod = md;
                    fieldRecord.firstWriteLocation = mc.getLocation(expr);
                    fieldRecord.constant = Nodes.getConstant(Nodes.getChild(expr, expr.getArguments().size()-1));
                    fields.put(fd.getName(), fieldRecord);
                } else {
                    if(fieldRecord.constant != null) {
                        Object constant = Nodes.getConstant(Nodes.getChild(expr, expr.getArguments().size()-1));
                        if(!Objects.equals(fieldRecord.constant, constant))
                            fieldRecord.constant = null;
                    }
                }
            }
        }
    }
    
    @FieldVisitor
    public void visit(FieldContext fc, FieldDefinition fd, TypeDefinition td, FieldStats fs) {
        if(fd.isSynthetic())
            return;
        int flags = fs.getFlags(fd);
        if(Flags.testAny(flags, FieldStats.UNRESOLVED) || hasAnnotation(fd)) {
            return;
        }
        boolean isConstantType = fd.getFieldType().isPrimitive() || Types.is(fd.getFieldType(), String.class);
        if(!Flags.testAny(flags, FieldStats.ACCESS)) {
            if(fd.isStatic() && fd.isFinal() && isConstantType)
                return;
            // Autogenerated by javacc 
            if(fd.getName().equals("lengthOfMatch") && td.getName().endsWith("TokenManager"))
                return;
            fc.report(fd.isPublic() || fd.isProtected() ? "UnusedPublicField" : "UnusedPrivateField", 0);
            return;
        }
        FieldRecord fieldRecord = fields.get(fd.getName());
        if (fieldRecord != null && !fd.isStatic() && fd.isFinal() && fieldRecord.constant != null) {
            fc.report("FieldShouldBeStatic", 0, Roles.METHOD.create(fieldRecord.firstWriteMethod),
                Roles.LOCATION.create(fieldRecord.firstWriteLocation));
            return;
        }
        if(!Flags.testAny(flags, FieldStats.READ)) {
            // Autogenerated by javacc 
            if(fd.getName().startsWith("jj") && td.getName().endsWith("TokenManager"))
                return;
            if(fd.getName().equals("errorCode") && td.getSimpleName().equals("TokenMgrError"))
                return;
            WarningAnnotation<?>[] anno = {};
            int priority = 0;
            String warningType = fd.isPublic() || fd.isProtected() ? "UnreadPublicField" : "UnreadPrivateField";
            if (fieldRecord != null) {
                anno = new WarningAnnotation[] { Roles.METHOD.create(fieldRecord.firstWriteMethod),
                        Roles.LOCATION.create(fieldRecord.firstWriteLocation) };
            }
            if(fd.isFinal() && fd.isPublic()) {
                priority += 10;
                if(fd.isStatic()) {
                    priority += 10;
                }
            }
            fc.report(warningType, priority, anno);
        }
    }

    private static boolean hasAnnotation(FieldDefinition fd) {
        for(CustomAnnotation ca : fd.getAnnotations()) {
            TypeReference annoType = ca.getAnnotationType();
            if(annoType.getPackageName().equals(AssertWarning.class.getPackage().getName()))
                continue;
            if(annoType.getSimpleName().equalsIgnoreCase("nonnull") ||
                   annoType.getSimpleName().equalsIgnoreCase("notnull") ||
                   annoType.getSimpleName().equalsIgnoreCase("nullable") ||
                   annoType.getSimpleName().equalsIgnoreCase("checkfornull"))
                continue;
            return true;
        }
        return false;
    }
}
